
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop #none #create-drop
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

