
spring:
  datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:hsqldb:mem:db;
    username: sa
#    password: sa
    password: 
    name: 
  jpa:
    hibernate:
      ddl-auto: create #none validate update create create-drop
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_schema: ''

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  hbm2ddl:
    auto: create-drop

